name: Problem template
description: Document a problem that you think needs solving for users of the web
labels: ["problem"]
body:

  - type: textarea
    id: description
    attributes:
      label: Describe the web problem you think needs solving
      description: |
        Just one or two sentences is often sufficient. Simple markdown only please (inline formatting, links, lists).
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Describe some use cases and requirements in detail
      description: |
        A use case is a description of a user facing a problem for which we don’t yet have a good solution; that is, a use case is an actual user wanting to do something. See [Sandboxed Filesystem use cases?](https://lists.w3.org/Archives/Public/public-webapps/2012JulSep/0835.html) for an example of how to describe use cases and requirements related to a specific problem.
    validations:
      required: false
