name: Create Cross-Repo Issue on Horizontal Label

on:
  issues:
    types: [labeled]

jobs:
  create-issue:
    if: github.event.label.name == 'Horizontal review requested'
    runs-on: ubuntu-latest

    permissions:
      issues: write  # Still needed to read source issue

    steps: # @@ use https://w3c.github.io/common-labels.json instead of harcoding GH repo
    - name: Create new issue in w3cping/privacy-request
      run: |
        gh issue create \
          --repo "w3cping/privacy-request" \
          --title "${{ github.event.issue.title }}" \
          --body "This issue was created because the 'horizontal review requested' label was added to ${{ github.event.issue.html_url }}" \
          --label "charter"
      env:
        GITHUB_TOKEN: ${{ secrets.W3CBOT_TOKEN }}
    - name: Create new issue in w3c/a11y-request
      run: |
        gh issue create \
          --repo "w3c/a11y-request" \
          --title "${{ github.event.issue.title }}" \
          --body "This issue was created because the 'horizontal review requested' label was added to ${{ github.event.issue.html_url }}" \
          --label "charter"
      env:
        GITHUB_TOKEN: ${{ secrets.W3CBOT_TOKEN }}
    - name: Create new issue in w3c/w3c/i18n-request
      run: |
        gh issue create \
          --repo "w3c/i18n-request" \
          --title "${{ github.event.issue.title }}" \
          --body "This issue was created because the 'horizontal review requested' label was added to ${{ github.event.issue.html_url }}" \
          --label "charter"
      env:
        GITHUB_TOKEN: ${{ secrets.W3CBOT_TOKEN }}
    - name: Create new issue in w3c/security-request
      run: |
        gh issue create \
          --repo "w3c/security-request" \
          --title "${{ github.event.issue.title }}" \
          --body "This issue was created because the 'horizontal review requested' label was added to ${{ github.event.issue.html_url }}" \
          --label "charter"
      env:
        GITHUB_TOKEN: ${{ secrets.W3CBOT_TOKEN }}
    - name: Create new issue in w3ctag/design-reviews
      run: |
        gh issue create \
          --repo "w3ctag/design-reviews" \
          --title "${{ github.event.issue.title }}" \
          --body "This issue was created because the 'horizontal review requested' label was added to ${{ github.event.issue.html_url }}" \
          --label "charter"
      env:
        GITHUB_TOKEN: ${{ secrets.W3CBOT_TOKEN }}
